easy_admin:
    entities:
        Category:
            #disabled_actions: ['delete', 'edit', 'restock']
            class: Mcc\DataSourceBundle\Entity\Category
            list:
                fields:
                    ['id', 'name']